### ISSUE TITLE
First bug report

### ISSUE THREAD

**Issue by ghost** [deeps96/SensorMax#2]
Hi @deeps96 I found this verry first bug on  the most recent version and that's how to reproduce it, in German:

```
- Bei den Sensorgruppen zwei oder mehr Sensoren auswählen (z.B. Beschleunigung und Gravitation)
- Messen
- Stoppen
- Neue Messung starten
```

After that, the app crashes immediately.

BTW:
Its better do don't commt compiled binaries. Concider using the Release feature of GitHub, please.

Greetings
mwuttke97

**Comment by deeps96** [comment]
Im working on it.

**Comment by deeps96** [comment]
Bug fixed. Now searching, how to delete folders from git...

**Comment by deeps96** [comment]
no chance to delete this ******\* bin - folder.
